# Generated by Django 5.0.2 on 2024-02-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20240206_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compus',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
