# Generated by Django 5.0.2 on 2024-02-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_compus_marca_alter_task_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField(blank=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('Documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.aprendiz')),
                ('Serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.compus')),
            ],
        ),
    ]
