# Generated by Django 5.0.2 on 2024-02-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_prestamo_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Serial',
            field=models.CharField(max_length=20),
        ),
    ]
