# Generated by Django 5.0.2 on 2024-03-07 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_prestamo_documento_alter_prestamo_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.aprendiz'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='hora_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
