# Generated by Django 5.0.2 on 2024-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_prestamo_documento_alter_prestamo_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Documento',
            field=models.CharField(max_length=20),
        ),
    ]
