# Generated by Django 5.0.2 on 2024-03-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_prestamo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.aprendiz'),
        ),
    ]
