# Generated by Django 5.0.3 on 2024-03-13 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_prestamo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.compus'),
        ),
    ]
